version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}           
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}     
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local