name: Publish Docker image

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    build-container:
        name: Build container
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Create .ENV file
              run: |
                echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
                echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env
                echo "DRIVER_DB=${{ secrets.DRIVER_DB }}" >> .env
                echo "MYSQL_URL=${{ secrets.MYSQL_URL }}" >> .env
                echo "MYSQL_DB=${{ secrets.MYSQL_DB }}" >> .env
                echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
                echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
                echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
                echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Build and push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: mlsants/goappmodular:latest, mlsants/goappmodular:${{ github.run_number }} 